# Linear Algebra

## What is a vector?

A vector is an arrow in space with a specific direction and lenght, often representing a piece of data. We declare a vector this way:
- $\vec{v} = \begin{bmatrix}x \\ y\end{bmatrix}$.

In [1]:
# Example 4-1 Declaring a vector in Python
v = [3,2]
print(v)

[3, 2]


In [2]:
# Example 4-2 Declaring a vector in Python using NumPy
import numpy as np
v = np.array([3, 2])
print(v)

[3 2]


We can declare vectors that have more than 2 dimensions, like the following:
- $\vec{v} = \begin{bmatrix}x \\ y \\ z\end{bmatrix}$.

In [3]:
# Example 4-3 Declaring a three-dimensional vector in Python using NumPy
import numpy as np
v = np.array([4, 1, 2])
print(v)

[4 1 2]


In [4]:
# Example 4-4 Declaring a five-dimensional vector in Python using NumPy
import numpy as np
v = np.array([4, 1, 2, 5, 7])
print(v)

[4 1 2 5 7]


### Adding and Combining Vectors

If we want to combine vectors we simply need to add the respective x-values and y-values into a new vector. We can visually do this by connecting graphically the second to the first. The point we end up is a new vector, the result of summing the two vectors.
The order of operation does not matter.

In [5]:
# Example 4-5 Adding two vectors in Python using NumPy
import numpy as np
v = np.array([3, 2])
w = np.array([2, -1])
v_plus_w = v + w
print(v_plus_w)

[5 1]


### Scaling Vectors

Scaling is growing or shrinking a vector's lenght. We do it by multiplying or scaling it with a single value, known as a scalar. Mathematically, we simply multiply each element of our vectory by the scalar value.

In [6]:
# Exampkle 4-6 Scaling a number in Python using NumPy
import numpy as np
v = np.array([3, 1])
scaled_v = v * 2.0
print(scaled_v)

[6. 2.]


It is important to note that scaling a vector does not change its direction, only its magnitude apart when we multiply it by a negative number which flips it.

### Span and Linear Dependence

These two operations, adding two vectors and scaling them, allows us to create whatever vector we want. This span, is in most cases unlimited. This applies when we have linearly indipendent vectors, so, when their directions are different. Otherwise, when they are on the same line, we are stuck on that line, whatever we add or use as a scaling value, at most we can go to negative values, that is because they are linearly dependent.

When we have vectors that are linearly dependent on a 3 or more dimensions, we often get stuck on a plane in a smaller number of dimensions. And, we do care about linear dependence because a lot of problems become unsolvable or difficult when vectors are linearly indipendent. We will use the determinant to check for linear dependence.

## Linear Transformations

The concept of adding two vectors with fixed direction in ordeer to get different vectors is important. Indeed, we can get whatever vector we want execept in cases of linear dependence. This means we can use a vector to transform another vector in a function-like manner.

### Basis Vectors

Let's say we have two simple vectors $\hat{i}$ and $\hat{j}$ and call them $basis$ $vectors$, which are used to describe transformations on other vectors. They tipically have a lenght of 1 and point in perpendicular positive directions. These simple vectors are our building blocks, and are expressed (or packaged) in a $2x2$ matrix:

- $\hat{i} = \begin{bmatrix}1 \\ 0\end{bmatrix}$;
- $\hat{j}= \begin{bmatrix}0 \\ 1\end{bmatrix}$,
- $basis$ $vector$ $= \begin{bmatrix}1,0\\0,1\end{bmatrix}$.

With this in mind, let's call the result of this matrix our vector v, $\hat{v}$, which points at $(1,1)$. Now, we can stretch our simple vectors in order to allow our vector $\hat{v}$ to land at $(3,2)$:
- $\hat{i} = 3*\begin{bmatrix}1 \\ 0\end{bmatrix} = \begin{bmatrix}3 \\ 0\end{bmatrix}$;
- $\hat{j} = 2*\begin{bmatrix}0 \\ 1\end{bmatrix} = \begin{bmatrix}0 \\ 2\end{bmatrix}$,
- $\hat{v} = \begin{bmatrix}3 \\ 0\end{bmatrix} + \begin{bmatrix}0 \\ 2\end{bmatrix} = \begin{bmatrix}3,0\\0,2\end{bmatrix}$.

It is important to note that we cannot have transformations that are nonlinear, resultying then in curvy or squiggly transformations that no longer respect a straight line.

## Matrix Vector Multiplication

We can transform an existing vector v given basis vectors i and j packaged as a matrix. This transformation is known as matrix vector multiplication. It is a shortcut for adding together i and j and then scaling it with the vector v.
NumPy populates the matrix as a row rather than a column, so, we need to transpose them if we want to break out the basis vector.

In [11]:
# Example 4-7 Matrix vector multiplication in NumPy
import numpy as np

basis = np.array([[3, 0],
                  [0, 2]]
                )

v = np.array([1, 1])

new_vector_v = basis.dot(v)
print(new_vector_v)

[3 2]


In [25]:
# Example 4-8 Separating the basis vectors and applying them as a transformation
import numpy as np
i_hat = np.array([2, 0])
j_hat = np.array([0, 3])
basis = np.array([i_hat, j_hat]).transpose()
print(basis)
v = np.array([1, 1])
new_vector_v = basis.dot(v)
print(new_vector_v)

[[2 0]
 [0 3]]
[2 3]


In [44]:
# Example 4-9 Transforming a vector using NumPy
import numpy as np

i_hat = np.array([1, 0]) * 2
print(i_hat)
j_hat = np.array([0, 1]) * 3
print(j_hat)
basis = np.array([i_hat, j_hat]).transpose()
print(basis)
v = np.array([2, 1])
new_vector_v = basis.dot(v)
print(new_vector_v)

[2 0]
[0 3]
[[2 0]
 [0 3]]
[4 3]


In [27]:
# Example 4-10 A more complicated transformation
import numpy as np

i_hat = np.array([2, 3])
j_hat = np.array([2, -1])
basis = np.array([i_hat, j_hat]).transpose()
print(basis)

v = np.array([2, 1])
new_vector_v = basis.dot(v)
print(new_vector_v)

[[ 2  2]
 [ 3 -1]]
[6 5]


### Matrix Multiplication

We learned how to multiply a vector (vector v) and a matrix (basis vector). Let's now learn how to multiply different matrix together.

In [39]:
# Example 4-11 Combining two transformations
import numpy as np

# First matrix composed of simple vectors
i_hat1 = np.array([0, 1])
j_hat1 = np.array([-1, 0])

transform1 = np.array([i_hat1, j_hat1]).transpose()
print(transform1)

# Second matrix composed of simple vectors
i_hat2 = np.array([1, 0])
j_hat2 = np.array([1, 1])

transform2 = np.array([i_hat2, j_hat2]).transpose()
print(transform2)

# Combine these two matrices
combined = transform2 @ transform1

# Multiply it with our vector v
v = np.array([1, 2])

print(combined.dot(v))

[[ 0 -1]
 [ 1  0]]
[[1 1]
 [0 1]]
[-1  1]


In [40]:
# Example 4-12 Applying the transformation in reverse
import numpy as np

i_hat1 = np.array([0, 1])
j_hat1 = np.array([-1, 0])

transform1 = np.array([i_hat1, j_hat1]).transpose()
print(transform1)

i_hat2 = np.array([1, 0])
j_hat2 = np.array([1, 1])

transform2 = np.array([i_hat2, j_hat2]).transpose()
print(transform2)

combined = transform1 @ transform2

v = np.array([1, 2])

print(combined.dot(v))

[[ 0 -1]
 [ 1  0]]
[[1 1]
 [0 1]]
[-2  3]


### Determinants

Determinants describe how much a sampled area in a vector space changes in scale with with linear transformations.

In [2]:
# Example 4-13 Calculating determinant
from numpy.linalg import det
from numpy import array

i_hat = array([3, 0])
j_hat = array([0, 2])

basis = array([i_hat, j_hat]).transpose()
print(basis)

determinant = det(basis)
print(determinant)

[[3 0]
 [0 2]]
6.0


Simple shears and rotations shouldn't affect the determinant, as the area will not change.

In [4]:
# Example 4-14 A determinant for a shear
from numpy.linalg import det
from numpy import array

i_hat = array([1, 0])
j_hat = array([1, 1])

basis = array([i_hat, j_hat]).transpose()
print(basis)

determinant = det(basis)
print(determinant)

[[1 1]
 [0 1]]
1.0


But the scaling will increase or decrease the determinant, as that will increase or decrease the sampled area. When the orientation flips, then the determinant will be negative.

In [6]:
# Example 4-15 A negative determinant
from numpy.linalg import det
from numpy import array

i_hat = array([-2, 1])
j_hat = array([1, 2])

basis = array([i_hat, j_hat]).transpose()
print(basis)

determinant = round(det(basis), 2)
print(determinant)

[[-2  1]
 [ 1  2]]
-5.0


But by far the most critical piece of information the determinant tells you is whether the transformation is linearly dependent or not. If you have a determinant of zero, that means all of the space has been squished into a lesser dimension.

In [8]:
# Example 4-16 A determinant of zero
from numpy.linalg import det
from numpy import array

i_hat = array([-2, 1])
j_hat = array([3, -1.5])

basis = array([i_hat, j_hat]).transpose()
print(basis)

determinant = det(basis)
print(determinant)

[[-2.   3. ]
 [ 1.  -1.5]]
0.0


So testing for a zero determinant is highly helpful to determine if a transformation has linear dependence. When you encounter this, you will likely find a difficult or unsolvable problem on your hands.

### Special Types of Matrices

We have different kind of matrices:
- Square matrix;
- Identity matrix;
- Inverse matrix;
- Diagonal matrix;
- Triangular matrix;
- Sparse matrix.

#### Square matrix

The square matrix is a matrix that has an equal number of rows and columns. They are primarily used to represent linear transformations and are a requirment for many operations (es. eigendecomposition).
Here an example: \begin{bmatrix}3&0&9\\0&2&4\\3&5&8\end{bmatrix}

#### Identity matrix

The identity matrix is a square matrix that has a diagonal of 1s while the other values are 0. They play a big role in solving system of equations since the identity matrix essentially represents the result of a linear transformation, as will be explained later.
Here an example: \begin{bmatrix}1&0&0\\0&1&0\\0&0&1\end{bmatrix}

#### Inverse matrix

An inverse matrix is just a matrix that undoes the transformation of another matrix. Let's say we have a matrix called A:
- $A$: \begin{bmatrix}4&2&4\\5&3&7\\9&3&6\end{bmatrix}

Then, the inverse of $A$ is defined as $A^{-1}$ and if we multiply it with the original matrix A we end up with the identity matrix:
- $A^{-1}$: \begin{bmatrix}-\dfrac{1}{2}&0&\dfrac{1}{3}\\5.5&-2&\dfrac{4}{3}\\-2&1&\dfrac{1}{3}\end{bmatrix}

#### Diagonal matrix

Similar to identity matrix is the diagonal matrix, which has a diagonal of nonzero values while the rest of the values are 0.
Here an example: \begin{bmatrix}4&0&0\\0&3&0\\0&0&6\end{bmatrix}

#### Triangular matrix

Triangular matrix has a diagonal of nonzero values in front of a triangle of values, while the rest of the values are 0.
Here an example:
\begin{bmatrix}4&2&4\\0&3&7\\0&0&6\end{bmatrix}

#### Sparse matrix

There are matrices that are mostrly zeros and have very few nonzero elements. These are called sparse matrix. From a computing standpoint they provide opportunities to create efficiency. Indeed, if a matrix has mostly 0s, a sparse matrix implementation will just keep track of the cells that are nonzero. Thus, when we have large matrices that are sparse we might explicitly use a sparse function to create our matrix.
Here an example: \begin{bmatrix}0&0&4\\0&0&0\\0&0&0\\0&0&0\end{bmatrix}

### System of Equations and Inverse Matrices

One of the usecases of linear algebra is to solve system of equations. Let's say we jave this system:
- $4x + 2y + 4z = 44$;
- $5x + 3y + 7z = 56$;
- $9x + 3y + 6z = 72$.

To solve it through linear algebra we need to express this problem in terms of matrices. So, we need to extract the coefficients into matriix $A$, the values on the right side of the equation into matrix $B$ and the unknown variables into matrix $X$:
- $A$ = \begin{bmatrix}4&2&4\\5&3&7\\9&3&6\end{bmatrix}
- $B$ = \begin{bmatrix}44\\56\\72\end{bmatrix}
- $X$ = \begin{bmatrix}x\\y\\z\end{bmatrix}

The function for a linear system of equations is $AX = B$. To solve it we need to re-arrange and solve for $X$, thus, we need to get rid of matrix $A$; we do so by multiplying both sides with its inverse, $A^{-1}$. Doing so, we end up with $X = B*A^{-1}$.
As anticipated before multiplying the inverse by its original matrix will create the identity matrix, which for linear algebra is the equivalent of 1.

In [11]:
# Example 4-17 Using SymPy to study the inverse and identity matrix
from sympy import *

# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72

A = Matrix([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])
print(A)

# Get the inverse
inverse = A.inv()
print(inverse)

# Get identity matrix
identity = inverse * A
print(identity)

Matrix([[4, 2, 4], [5, 3, 7], [9, 3, 6]])
Matrix([[-1/2, 0, 1/3], [11/2, -2, -4/3], [-2, 1, 1/3]])
Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])


In [15]:
# Example 4-18 Using NumPy to solve a system of equations
from numpy.linalg import inv
from numpy import array

# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72

A = array([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])

B = array([44,
           56,
           72])

# Get X -> $A^-1 * B
X = inv(A).dot(B)
print(X)  # X = 2, Y = 34 and Z = -8

[ 2. 34. -8.]


In [17]:
# Example 4-19 Using SymPy to solve a system of equations
from sympy import *

# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72

A = Matrix([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])

B = Matrix([44,
           56,
           72])

X = A.inv() * B
print(X)  # X = 2, Y = 34 and Z = -8

Matrix([[2], [34], [-8]])


### Eigenvectors and Eigenvalues

Matrix decomposition is breaking up a matrix into its basic components, much like factoring numbers (e.g. 10 can be factored to 2 * 5). This is helpful for tasks like finding the inverse and calculating determinants, as well as linear regressions. One of the methods to decompose a matrix is called $eigendecomposition$.
In $eigendecomposition$ there are two components, $eigenvalues$ and $eigenvectors$, denoted by $\lambda$ and $\nu$.
If we have a square matrix $A$, it has the following eigenvalue equation:
- $A\nu = \lambda\nu$.

In [21]:
# Example 4-20  Performing eigendecomposition in NumPy
from numpy import array, diag
from numpy.linalg import eig, inv

A = array([
    [1, 2],
    [4, 5]
])

eigenvals, eigenvecs = eig(A)

print(eigenvals)
print("\n")
print(eigenvecs)

[-0.46410162  6.46410162]


[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]


In order to recompose our original matrix we have to follow this formula:
- $A = Q^{-1}*\Lambda*Q$.

$Q$ is the eigenvectors, $\Lambda$ is the eigenvalues in diagonal form and $Q^{-1}$ is just the inverse of $Q$. In $\Lambda$ we are just padding the vector into a diagonal matrix.

In [24]:
# Example 4-21 Decomposing and recomposing in NumPy
from numpy import array, diag
from numpy.linalg import eig, inv

A = array([
    [1, 2],
    [4, 5]
])

eigenvals, eigenvecs = eig(A)

print(eigenvals)
print("\n")
print(eigenvecs)
print("\n")

Q = eigenvecs
inverse_Q = inv(Q)
V = diag(eigenvals)

original_matrix = Q @ V @ inverse_Q
print(original_matrix)

[-0.46410162  6.46410162]


[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]


[[1. 2.]
 [4. 5.]]
