# Linear Algebra

## What is a vector?

A vector is an arrow in space with a specific direction and lenght, often representing a piece of data. We declare a vector this way:
- $\vec{v} = \begin{bmatrix}x \\ y\end{bmatrix}$.

In [1]:
# Example 4-1 Declaring a vector in Python
v = [3,2]
print(v)

[3, 2]


In [2]:
# Example 4-2 Declaring a vector in Python using NumPy
import numpy as np
v = np.array([3, 2])
print(v)

[3 2]


We can declare vectors that have more than 2 dimensions, like the following:
- $\vec{v} = \begin{bmatrix}x \\ y \\ z\end{bmatrix}$.

In [3]:
# Example 4-3 Declaring a three-dimensional vector in Python using NumPy
import numpy as np
v = np.array([4, 1, 2])
print(v)

[4 1 2]


In [4]:
# Example 4-4 Declaring a five-dimensional vector in Python using NumPy
import numpy as np
v = np.array([4, 1, 2, 5, 7])
print(v)

[4 1 2 5 7]


### Adding and Combining Vectors

If we want to combine vectors we simply need to add the respective x-values and y-values into a new vector. We can visually do this by connecting graphically the second to the first. The point we end up is a new vector, the result of summing the two vectors.
The order of operation does not matter.

In [5]:
# Example 4-5 Adding two vectors in Python using NumPy
import numpy as np
v = np.array([3, 2])
w = np.array([2, -1])
v_plus_w = v + w
print(v_plus_w)

[5 1]


### Scaling Vectors

Scaling is growing or shrinking a vector's lenght. We do it by multiplying or scaling it with a single value, known as a scalar. Mathematically, we simply multiply each element of our vectory by the scalar value.

In [6]:
# Exampkle 4-6 Scaling a number in Python using NumPy
import numpy as np
v = np.array([3, 1])
scaled_v = v * 2.0
print(scaled_v)

[6. 2.]


It is important to note that scaling a vector does not change its direction, only its magnitude apart when we multiply it by a negative number which flips it.

### Span and Linear Dependence

These two operations, adding two vectors and scaling them, allows us to create whatever vector we want. This span, is in most cases unlimited. This applies when we have linearly indipendent vectors, so, when their directions are different. Otherwise, when they are on the same line, we are stuck on that line, whatever we add or use as a scaling value, at most we can go to negative values, that is because they are linearly dependent.

When we have vectors that are linearly dependent on a 3 or more dimensions, we often get stuck on a plane in a smaller number of dimensions. And, we do care about linear dependence because a lot of problems become unsolvable or difficult when vectors are linearly indipendent. We will use the determinant to check for linear dependence.

## Linear Transformations

The concept of adding two vectors with fixed direction in ordeer to get different vectors is important. Indeed, we can get whatever vector we want execept in cases of linear dependence. This means we can use a vector to transform another vector in a function-like manner.

### Basis Vectors

Let's say we have two simple vectors $\hat{i}$ and $\hat{j}$ and call them $basis$ $vectors$, which are used to describe transformations on other vectors. They tipically have a lenght of 1 and point in perpendicular positive directions. These simple vectors are our building blocks, and are expressed (or packaged) in a $2x2$ matrix:

- $\hat{i} = \begin{bmatrix}1 \\ 0\end{bmatrix}$;
- $\hat{j}= \begin{bmatrix}0 \\ 1\end{bmatrix}$,
- $basis$ $vector$ $= \begin{bmatrix}1,0\\0,1\end{bmatrix}$.

With this in mind, let's call the result of this matrix our vector v, $\hat{v}$, which points at $(1,1)$. Now, we can stretch our simple vectors in order to allow our vector $\hat{v}$ to land at $(3,2)$:
- $\hat{i} = 3*\begin{bmatrix}1 \\ 0\end{bmatrix} = \begin{bmatrix}3 \\ 0\end{bmatrix}$;
- $\hat{j} = 2*\begin{bmatrix}0 \\ 1\end{bmatrix} = \begin{bmatrix}0 \\ 2\end{bmatrix}$,
- $\hat{v} = \begin{bmatrix}3 \\ 0\end{bmatrix} + \begin{bmatrix}0 \\ 2\end{bmatrix} = \begin{bmatrix}3,0\\0,2\end{bmatrix}$.

It is important to note that we cannot have transformations that are nonlinear, resultying then in curvy or squiggly transformations that no longer respect a straight line.

## Matrix Vector Multiplication

We can transform an existing vector v given basis vectors i and j packaged as a matrix. This transformation is known as matrix vector multiplication. It is a shortcut for adding together i and j and then scaling it with the vector v.
NumPy populates the matrix as a row rather than a column, so, we need to transpose them if we want to break out the basis vector.

In [11]:
# Example 4-7 Matrix vector multiplication in NumPy
import numpy as np

basis = np.array([[3, 0],
                  [0, 2]]
                )

v = np.array([1, 1])

new_vector_v = basis.dot(v)
print(new_vector_v)

[3 2]


In [25]:
# Example 4-8 Separating the basis vectors and applying them as a transformation
import numpy as np
i_hat = np.array([2, 0])
j_hat = np.array([0, 3])
basis = np.array([i_hat, j_hat]).transpose()
print(basis)
v = np.array([1, 1])
new_vector_v = basis.dot(v)
print(new_vector_v)

[[2 0]
 [0 3]]
[2 3]


In [44]:
# Example 4-9 Transforming a vector using NumPy
import numpy as np

i_hat = np.array([1, 0]) * 2
print(i_hat)
j_hat = np.array([0, 1]) * 3
print(j_hat)
basis = np.array([i_hat, j_hat]).transpose()
print(basis)
v = np.array([2, 1])
new_vector_v = basis.dot(v)
print(new_vector_v)

[2 0]
[0 3]
[[2 0]
 [0 3]]
[4 3]


In [27]:
# Example 4-10 A more complicated transformation
import numpy as np

i_hat = np.array([2, 3])
j_hat = np.array([2, -1])
basis = np.array([i_hat, j_hat]).transpose()
print(basis)

v = np.array([2, 1])
new_vector_v = basis.dot(v)
print(new_vector_v)

[[ 2  2]
 [ 3 -1]]
[6 5]


### Matrix Multiplication

We learned how to multiply a vector (vector v) and a matrix (basis vector). Let's now learn how to multiply different matrix together.

In [39]:
# Example 4-11 Combining two transformations
import numpy as np

# First matrix composed of simple vectors
i_hat1 = np.array([0, 1])
j_hat1 = np.array([-1, 0])

transform1 = np.array([i_hat1, j_hat1]).transpose()
print(transform1)

# Second matrix composed of simple vectors
i_hat2 = np.array([1, 0])
j_hat2 = np.array([1, 1])

transform2 = np.array([i_hat2, j_hat2]).transpose()
print(transform2)

# Combine these two matrices
combined = transform2 @ transform1

# Multiply it with our vector v
v = np.array([1, 2])

print(combined.dot(v))

[[ 0 -1]
 [ 1  0]]
[[1 1]
 [0 1]]
[-1  1]


In [40]:
# Example 4-12 Applying the transformation in reverse
import numpy as np

i_hat1 = np.array([0, 1])
j_hat1 = np.array([-1, 0])

transform1 = np.array([i_hat1, j_hat1]).transpose()
print(transform1)

i_hat2 = np.array([1, 0])
j_hat2 = np.array([1, 1])

transform2 = np.array([i_hat2, j_hat2]).transpose()
print(transform2)

combined = transform1 @ transform2

v = np.array([1, 2])

print(combined.dot(v))

[[ 0 -1]
 [ 1  0]]
[[1 1]
 [0 1]]
[-2  3]
